// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Yb9f4XadBRi1duZQgFH-8RuRzcBU_kU',
    appId: '1:568625963282:web:e4d61b5f3d8c9d72e413cb',
    messagingSenderId: '568625963282',
    projectId: 'fir-login-8fc8a',
    authDomain: 'fir-login-8fc8a.firebaseapp.com',
    storageBucket: 'fir-login-8fc8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn5rOXnkBTa1EE_G45Ojhr3Fao1nCZGrQ',
    appId: '1:568625963282:android:e974eb4797638c89e413cb',
    messagingSenderId: '568625963282',
    projectId: 'fir-login-8fc8a',
    storageBucket: 'fir-login-8fc8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALOdbWyfZ8ITc17sLzTnM50HIzX8OCfNo',
    appId: '1:568625963282:ios:1aaec5d517506afae413cb',
    messagingSenderId: '568625963282',
    projectId: 'fir-login-8fc8a',
    storageBucket: 'fir-login-8fc8a.appspot.com',
    iosClientId: '568625963282-1a990akkiv7e8015l6mvg31comppkaf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.formfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALOdbWyfZ8ITc17sLzTnM50HIzX8OCfNo',
    appId: '1:568625963282:ios:1aaec5d517506afae413cb',
    messagingSenderId: '568625963282',
    projectId: 'fir-login-8fc8a',
    storageBucket: 'fir-login-8fc8a.appspot.com',
    iosClientId: '568625963282-1a990akkiv7e8015l6mvg31comppkaf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.formfirebase',
  );
}
